### ISSUE TITLE
Inventory-view

### ISSUE THREAD

**Issue by magnuskiro** [Studentmediene/barweb#17]
create view for inventory of the bar.

make sure it has:
* all available items
* amount of each
* price of each
* sum of inventory

**Comment by Agfct** [comment]
Added a Inventory view + table. 
Basic Inventory view complete, but actual user feedback is required to add additional functionalities.

The Modal for adding an item could use some modifications: 
Like adding an "add 24" on the side of the amount panel.
But feedback is requried before making unnecessary changes. :)
