### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by magnuskiro** [Studentmediene/barweb#6]
Create statistics based on transactions. and balance.

**Comment by TheSimoms** [comment]
Should this issue be considered resolved?

**Comment by magnuskiro** [comment]
If you think the implementation is finished you need to do user testing or approval from stakeholders. Aka ask the Barsjef if it seems ok.

**Comment by TheSimoms** [comment]
Damn it! @haakonmt, you've got work to do.
